# Generated by Django 3.0.6 on 2020-05-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0002_auto_20200510_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categ_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_variant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variant_of', to='product.ProductVariant'),
        ),
    ]
